### ISSUE TITLE
Allow case insensitive URL paths

### ISSUE THREAD

**Issue by Spacey4K** [MaticBabnik/timetable-vue#2]
Going to https://v.sync.si/t/classes/r3b instead of `R3B` gives an error:
> Error! (try selecting the timetable again)

**Comment by MaticBabnik** [comment]
![tenor (11)](https://user-images.githubusercontent.com/19249905/160715514-1e076b64-70b7-4fd3-a4eb-56ca8aafcc76.gif)

**Comment by MaticBabnik** [comment]
#3 Is now deployed on [my instance](https://v.sync.si/). It should fix `/t/classes/<name>` and `/t/clasrooms/<name>`. I still need to find a sane way to make teacher names URL safe and case insensitive.
