### ISSUE TITLE
Switch between weeks

### ISSUE THREAD

**Issue by aikenahac** [MaticBabnik/timetable-vue#4]
Add option to switch between weeks

**Comment by MaticBabnik** [comment]
https://github.com/MaticBabnik/easistent-tt/issues/4
Will look into when I have some spare time.

**Comment by ghost** [comment]
This problem has been amplified in recent times, due to the schedule changing every day!! (It would be nice to know what the Monday holds on a Sunday like today!)

**Comment by MaticBabnik** [comment]
> This problem has been amplified in recent times, due to the schedule changing every day!! (It would be nice to know what the Monday holds on a Sunday like today!)

Well actually unlike eAsistent the api starts showing the next week's timetable on sunday.

Also, https://github.com/MaticBabnik/easistent-tt/pull/5 (deployed on https://v3.vegova.sync.si/) added multiple week support to the backend and I am currently working on a new version of the frontend. It should be done this month.


epic preview:
![image](https://user-images.githubusercontent.com/19249905/191074529-8eb0600a-292f-4666-b8f7-65ece1e2d445.png)

**Comment by MaticBabnik** [comment]
this month:tm:
i must be operating on valve time
